::!(c) Denis Kuzmin <x-3F@outlook.com> github.com/3F
@echo off&set ee=gnt.core&set ef="%temp%\%ee%1.10.0%random%%random%"&set -=GetNuTool
setlocal enableDelayedExpansion&set _0=MSBuild&set eg=%*&set eh=%~1&if "!eh!"=="-unpack" goto eo
if "!eh!"=="" call :ep
set "ei=!eg!"&call :eq "/help" "-help" "/h" "-h" "/?" "-?"&set ej=%-%/1.10.0 /p:info=no;use=&if "!ei!" NEQ "!eg!" set eg=~!ej!?
set ek="!eg:~0,1!"&if !ek!=="+" call :er install
if !ek!=="*" call :er run
if !ek!=="~" call :er touch
if defined eg if !ek! NEQ "/" if !ek! NEQ "-" set eg=/p:ngpackages=!eg!
set "el="&for /F "tokens=*" %%i in ('h%_0% -only-path 2^>^&1')do 2>nul set el="%%i"
if exist !el! goto es
for %%v in (4.0,14.0,12.0)do (for /F "usebackq tokens=2* skip=2" %%a in (`reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\%_0%\ToolsVersions\%%v" /v %_0%ToolsPath 2^>nul`)do (set el="%%~b\%_0%.exe"
if exist !el! goto es))
echo [x]Engine>&2
exit/B2
:es
set em=/noconlog&if "%debug%"=="true" set em=/v:q
call :et&call !el! %ef% /nologo /noautorsp !em! /p:wpath="%cd%/" !eg!&set en=!ERRORLEVEL!&del /Q/F %ef%&exit/B!en!
:eo
set ef="%cd%\%ee%"&echo +%ee% %cd%\
:et
setlocal disableDelayedExpansion
<nul set/P=>%ef%&set [=TaskCoreDllPath&set ]=Exists&set ;=%_0%ToolsPath&set .=Microsoft.Build.Tasks.&set ,=%_0%ToolsVersion&set :=tmode&set +=System&set {=Using&set }=Namespace&set _=Console.WriteLine(&set a=);var&set b=String&set c=package&set d=Environment&set e=){var&set f=);if(&set g=.IsNullOr&set h=foreach&set i=(var&set j=Attribute&set k==null&set l=Console.Error.WriteLine(&set m=return&set n=Append&set o=Path&set p=Combine&set q=Length&set r=false&set s=SecurityProtocol&set t=ServicePointManager&set u=Credential&set v=Directory&set w=.Create&set x=Console.Write(&set y=using&set z=Exception&set $=FileMode&set #=FileAccess&set @=Comparison&set `=StartsWith&set ?=)continue;var&set !=http://schemas.microsoft.com/&set _1=Reference Include="
<nul set/P=^<?xml version="1.0"?^>^<Project ToolsVersion="4.0" xmlns="%!%developer/%_0%/2003"^>^<PropertyGroup^>^<%-%^>1.10.0.5939+e5f5c45^</%-%^>^<%[% Condition="%]%('$(%;%)\%.%v$(%,%).dll')"^>$(%;%)\%.%v$(%,%).dll^</%[%^>^<%[% Condition="'$(%[%)'=='' and %]%('$(%;%)\%.%Core.dll')"^>$(%;%)\%.%Core.dll^</%[%^>^</PropertyGroup^>>>%ef%
for %%t in (get,install,run,touch,grab,pack)do <nul set/P=^<Target Name="%%t"^>^<K %:%="%%t"/^>^</Target^>>>%ef%
<nul set/P=^<%{%Task TaskName="K" TaskFactory="CodeTaskFactory" AssemblyFile="$(%[%)"^>^<ParameterGroup^>^<%:%/^>^</ParameterGroup^>^<Task^>^<%_1%%+%.Xml"/^>^<%_1%%+%.Xml.Linq"/^>^<%_1%WindowsBase"/^>^<%{% %}%="%+%"/^>^<%{% %}%="%+%.Text"/^>^<%{% %}%="%+%.IO"/^>^<%{% %}%="%+%.IO.Packaging"/^>^<%{% %}%="%+%.Linq"/^>^<%{% %}%="%+%.Net"/^>^<%{% %}%="%+%.Xml.Linq"/^>^<%{% %}%="%+%.Diagnostics"/^>^<Code Type="Fragment" Language="cs"^>^<![CDATA[if("$(logo)"!="no")%_%"\n%-% $(%-%)\n(c) 2015-2025  Denis Kuzmin <x-3F@outlook.com> github/3F\n"%a% K=" is not found ";var L=new %b%[]{"/_rels/","/%c%/","/[Content_Types].xml"};Action^<%b%^>M=N=^>{if("$(debug)"=="true")%_%N);};Func^<%b%,%b%^>O=P=^>P==""?null:P;var Q=O(@"$(wpath)")??@"$(%_0%Project%v%)";%d%.Current%v%=Q;Action^<%b%,%b%^>R=%d%.Set%d%Variable;R("%-%","$(%-%)");R("use","$(use)");R("debug","$(debug)"%a% S="id";var T="version";var U="$(info)"!="no";if(%:%!="pack"%e% V=@"$(ng%c%s)";var W=new %b%Builder(%f%%b%%g%WhiteSpace(V)%e% X=O(@"$(ngconfig)")??@"%c%s.config;.tools\%c%s.config";Action^<%b%^>Y=Z=^>{%h%%i% D in XDocument.Load(Z).Root.Descendants("%c%")%e% E=D.%j%(S%a% F=D.%j%(T%a% G=D.%j%("output"%a% H=D.%j%("sha1"%f%E=%k%){%l%"Invalid "+Z);%m%;}W.%n%(E.Value%f%F!%k%)W.%n%("/"+F.Value%f%>>%ef%
<nul set/P=H!%k%)W.%n%("?"+H.Value%f%G!%k%)W.%n%(":"+G.Value);W.%n%(';');}};%h%%i% Z in X.Split(';')%e% I=%o%.%p%(Q,Z%f%File.%]%(I)){Y(I);}else M(I+K);}if(W.%q%^<1){%l%"Empty .config + ng%c%s");%m% %r%;}V=W.To%b%();}var J=O(@"$(ngpath)")??"%c%s";var A=@"$(proxycfg)";%h%%i% B in Enum.GetValues(typeof(%s%Type)).Cast^<%s%Type^>()){try{%t%.%s%^|=B;}catch(NotSupported%z%){}}if("$(ssl3)"!="true")%t%.%s%^&=~(%s%Type)(48^|192^|768);Func^<%b%,WebProxy^>C=Z=^>{var d=Z.Split('@'%f%d.%q%^<=1)%m% new WebProxy(d[0],%r%%a% e=d[0].Split(':');%m% new WebProxy(d[1],%r%){%u%s=new Network%u%(e[0],e.%q%^>1?e[1]:null)};};Func^<%b%,%b%^>f=g=^>{var h=%o%.Get%v%Name(g%f%!%v%.%]%(h))%v%%w%%v%(h);%m% g;};Func^<%b%,%b%,%b%,%b%,bool^>i=(j,k,g,H)=^>{var l=%o%.GetFull%o%(%o%.%p%(Q,g??k??"")%a% m=%:%[0]=='t';if(m^&^&%v%.%]%(l))%v%.Delete(l,true%f%%v%.%]%(l)^|^|File.%]%(l)){if(U)%_%k+" use "+l);%m% true;}if(U)%x%j+" ... "%a% n=%:%=="grab";var o=n?f(l):%o%.%p%(%o%.GetTemp%o%(),Guid.NewGuid().To%b%());%y%%i% p=new WebClient()){try{if(!%b%%g%Empty(A)){p.Proxy=C(A);}p.Headers.Add("User-Agent","%-%/$(%-%)");p.UseDefault%u%s=true;if(p.Proxy!%k%^&^&p.Proxy.%u%s=%k%){p.Proxy.%u%s=%u%Cache.Default%u%s;}if(%d%.Get%d%Variable("ngserver")!%k%^|^|%d%.Get%d%Variable("proxycfg")!%k%)throw new %z%("denied");p.DownloadFile((O(@"$(ngserver)")??"https://www.nuget.org/api/v2/%c%/")+j,o);}catch(%z% q){%l%q.Message);%m% %r%;}}if(U)%_%l%f%H!%k%){%x%H+" ... ");%y%%i% r=%+%.Security.Cryptography.SHA1%w%()){W.Clear();%y%%i% s=new FileStream(o,(%$%)3,(%#%)1))%h%%i% t in r.ComputeHash(s))W.%n%(t.To%b%("x2"));%x%W.To%b%()%f%!W.To%b%().Equals(H,(%b%%@%)5)){%_%"[x]");%m% %r%;}%_%);}}if(n)%m% true;%y%%i% D=ZipPackage.Open(o,(%$%)3,(%#%)1)){%h%%i% u in D.GetParts()%e% v=Uri.UnescapeData%b%(u.Uri.Original%b%%f%L.Any(w=^>v.%`%(w,(%b%%@%)4))%?% x=%o%.%p%(l,v.TrimStart('/'));M("- "+v);%y%%i% y=u.GetStream((%$%)3,(%#%)1))%y%%i% z=File.OpenWrite(f(x))){try{y.CopyTo(z);}catch(FileFormat%z%)>>%ef%
<nul set/P={M("[x]?crc: "+x);}}}}File.Delete(o%f%%:%!="get"%e% a=l+"/.pkg.install."+(%o%.VolumeSeparatorChar==':'?"bat":"sh"%f%File.%]%(a)){M(%:%+" "+a%a% b=Process.Start(new ProcessStartInfo(a,"1 "+%:%+" \""+Q+"\" \""+l+"\""){UseShellExecute=%r%});b.WaitForExit();b.Dispose();}if(m){%v%.Delete(l,true%f%%v%.GetDirectories(l+"/../").%q%^<1)%v%.Delete(l+"/../");}}%m% true;};%h%%i% D in V.Split(';')){if(D==""%?% c=D.Split(new[]{':'},2%a% j=c[0].Split(new[]{'?'},2%a% g=c.%q%^>1?c[1]:null;var k=j[0].Replace('/','.').Trim();if(!%b%%g%Empty(J)){g=%o%.%p%(J,g??k);}if(!i(j[0],k,g,j.%q%^>1?j[1]:null)^&^&"$(break)"!="no")%m% %r%;}}else if(%:%=="pack"%e% _=".nuspec";var h=%o%.%p%(Q,@"$(ngin)"%f%!%v%.%]%(h)){%l%h+K);%m% %r%;}var KK=%v%.GetFiles(h,"*"+_).FirstOrDefault(%f%KK=%k%){%l%_+K+h);%m% %r%;}%_%_+" use "+KK%a% KL=XDocument.Load(KK).Root.Elements().FirstOrDefault(w=^>w.Name.LocalName=="metadata"%f%KL=%k%){%l%"metadata"+K);%m% %r%;}var KM=new %+%.Collections.Generic.Dictionary^<%b%,%b%^>();Func^<%b%,%b%^>KN=KO=^>KM.ContainsKey(KO)?KM[KO]:"";%h%%i% KP in KL.Elements())KM[KP.Name.LocalName.ToLower()]=KP.Value;if(!%+%.Text.RegularExpressions.Regex.IsMatch(KN(S),@"^\w+(?:[_.-]\w+)*$")){%l%"Invalid id");%m% %r%;}var KQ=KN(S)+"."+KN(T)+".nupkg";var KR=%o%.%p%(Q,@"$(ngout)"%f%!%b%%g%WhiteSpace(KR)){if(!%v%.%]%(KR)){%v%%w%%v%(KR);}KQ=%o%.%p%(KR,KQ);}%_%"Pack ... "+KQ);%y%%i% D=Package.Open(KQ,(%$%)2)%e% KS=new Uri("/"+KN(S)+_,(UriKind)2);D%w%Relationship(KS,0,"%!%packaging/2010/07/manifest");%h%%i% KT in %v%.GetFiles(h,"*.*",(SearchOption)1)){if(L.Any(w=^>KT.%`%(%o%.%p%(h,w.Trim('/')),(%b%%@%)4))%?% KU=KT.%`%(h,(%b%%@%)5)?KT.Substring(h.%q%).TrimStart(%o%.%v%SeparatorChar):KT;M("+ "+KU%a% u=D%w%Part(PackUriHelper%w%PartUri(new Uri(%b%.Join("/",KU.Split('\\','/').Select(Uri.EscapeData%b%)),(UriKind)2)),"application/octet",(CompressionOption)1);%y%%i% KV=u.GetStream())%y%%i% KW=new FileStream(KT,(%$%)3,(%#%)1)){KW.CopyTo(KV);}}var KX=D>>%ef%
<nul set/P=.PackageProperties;KX.Creator=KN("authors");KX.Description=KN("description");KX.Identifier=KN(S);KX.Version=KN(T);KX.Keywords=KN("tags");KX.Title=KN("title");KX.LastModifiedBy="%-%/$(%-%)";}}else %m% %r%;]]^>^</Code^>^</Task^>^</%{%Task^>^</Project^>>>%ef%
endlocal&exit/B0
:ep
set eg=%*&exit/B0
:er
call :ep !eg:~1!&if "!eg:~0,1!" NEQ "/" if "!eg:~0,1!" NEQ "-" if "!eg!" NEQ "" set eg=!eg! /t:%1&exit/B0
set eg=!ej!;logo=no !eg! /t:%1&exit/B0
:eq
if defined eg set eg=!eg:%~1=!
if "%~2" NEQ "" shift & goto eq
exit/B0